#ifndef __MAIN_NUCLEO_H__
#define __MAIN_NUCLEO_H__

#define IS_MIC_DATA_GPIO_Port GPIOC
#define IS_MIC_DATA_Pin GPIO_PIN_0
#define IS_MIC_DATA IS_MIC_DATA_GPIO_Port, IS_MIC_DATA_Pin
#define DATA_INTERRUPT_GPIO_Port GPIOC
#define DATA_INTERRUPT_Pin GPIO_PIN_1
#define DATA_INTERRUPT DATA_INTERRUPT_GPIO_Port, DATA_INTERRUPT_Pin

#endif